name: tests

on:
  push:
    branches:
      - main

env:
  COLUMNS: 120

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.9", "3.10", "3.11", "3.12"]
        torch_version: ["2.5.1+cpu", "2.6.0+cpu", "2.7.1+cpu", "2.8.0+cpu"]
        # If certain torch/py combos are invalid, exclude them here:
        # exclude:
        #   - python_version: '3.9'
        #     torch_version: '2.8.0+cpu'

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install system tools (curl, jq, bc)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq bc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # project deps
          python -m pip install '.[test,docs,dev,extended]'
          # test pretty output
          python -m pip install pytest-pretty
          # torch (CPU wheels)
          python -m pip install "torch==${{ matrix.torch_version }}" -f https://download.pytorch.org/whl/torch
          # choose compatible triton for torch<2.7
          TORCH_VERSION_MAJOR_MINOR=$(python - <<'PY'
          import torch, re
          v = re.sub(r'\+.*$', '', torch.__version__)
          print('.'.join(v.split('.')[:2]))
          PY
          )
          if [[ $(echo "$TORCH_VERSION_MAJOR_MINOR < 2.6" | bc -l) -eq 1 ]]; then
            python -m pip install "triton==3.1"
          elif [[ $(echo "$TORCH_VERSION_MAJOR_MINOR < 2.7" | bc -l) -eq 1 ]]; then
            python -m pip install "triton==3.2"
          fi
          python -m pip list

      - id: measurement_after_deps
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement

      - name: Install skorch
        run: |
          python -m pip install .

      - id: measurement_after_skorch
        name: Record Measurement After Install skorch
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install skorch
          task: get-measurement

      - name: Test with pytest
        run: |
          pytest

      - id: measurement_after_tests
        name: Record Measurement After Test with pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Test with pytest
          task: get-measurement

      - id: display_results
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: |
          echo '${{ steps.display_results.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
