name: tests
on:
  push:
    branches:
      - main

env:
  COLUMNS: 120
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: "python -m pip install --upgrade pip\npython -m pip install '.[test,docs,dev,extended]'\n\
          python -m pip install pytest-pretty \npython -m pip install torch==${{ matrix.torch_version\
          \ }} -f https://download.pytorch.org/whl/torch\nTORCH_VERSION_MAJOR_MINOR=$(python\
          \ -c \"import torch; v=torch.__version__.split('+')[0]; print('.'.join(v.split('.')[:2]))\"\
          )\nif [[ $(echo \"$TORCH_VERSION_MAJOR_MINOR < 2.6\" | bc -l) -eq 1 ]];\
          \ then\n  python -m pip install \"triton==3.1\"\nelif [[ $(echo \"$TORCH_VERSION_MAJOR_MINOR\
          \ < 2.7\" | bc -l) -eq 1 ]]; then\n  python -m pip install \"triton==3.2\"\
          \nfi\npython -m pip list\n"
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Install skorch
        run: 'python -m pip install .

          '
      - id: measurement-6
        name: Record Measurement After Install skorch
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install skorch
          task: get-measurement
      - name: Test with pytest
        run: 'pytest

          '
      - id: measurement-8
        name: Record Measurement After Test with pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Test with pytest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        torch_version:
          - 2.5.1+cpu
          - 2.6.0+cpu
          - 2.7.1+cpu
          - 2.8.0+cpu
