name: HF integration tests
on:
  push:
    branches:
      - master

jobs:
  hf-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Requirements
        run:
          "python -m pip install torch -f https://download.pytorch.org/whl/torch_stable.html

          python -m pip install transformers tokenizers huggingface_hub

          python -m pip install .

          "
      - id: measurement-4
        name: Record Measurement After Install Requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install Requirements
          task: get-measurement
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        name: run HF integration test
        run: python scripts/hf-integration-tests.py
        continue-on-error: true
      - id: measurement-6
        name: Record Measurement After run HF integration test
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: run HF integration test
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    timeout-minutes: 10
